export const CHANGE_LOCALE = 'CHANGE_LOCALE';
export const DEFAULT_LOCALE = 'en';

//Login Process Actions
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const PERSONALINFO_SAVE_REQUEST = 'PERSONALINFO_SAVE_REQUEST';
export const PERSONALINFO_SAVE_SUCCESS = 'PERSONALINFO_SAVE_SUCCESS';
export const PERSONALINFO_SAVE_FAIL = 'PERSONALINFO_SAVE_FAIL';

export const ABOUTME_SAVE_REQUEST = 'ABOUTME_SAVE_REQUEST';
export const ABOUTME_SAVE_SUCCESS = 'ABOUTME_SAVE_SUCCESS';
export const ABOUTME_SAVE_FAIL = 'ABOUTME_SAVE_FAIL';

export const CONTACTINFO_SAVE_REQUEST = 'CONTACTINFO_SAVE_REQUEST';
export const CONTACTINFO_SAVE_SUCCESS = 'CONTACTINFO_SAVE_SUCCESS';
export const CONTACTINFO_SAVE_FAIL = 'CONTACTINFO_SAVE_FAIL';

export const EDUCATION_SAVE_REQUEST = 'EDUCATION_SAVE_REQUEST';
export const EDUCATION_SAVE_SUCCESS = 'EDUCATION_SAVE_SUCCESS';
export const EDUCATION_SAVE_FAIL = 'EDUCATION_SAVE_FAIL';

export const SKILL_SAVE_REQUEST = 'SKILL_SAVE_REQUEST';
export const SKILL_SAVE_SUCCESS = 'SKILL_SAVE_SUCCESS';
export const SKILL_SAVE_FAIL = 'SKILL_SAVE_FAIL';

export const WORKEXP_SAVE_REQUEST = 'WORKEXP_SAVE_REQUEST';
export const WORKEXP_SAVE_SUCCESS = 'WORKEXP_SAVE_SUCCESS';
export const WORKEXP_SAVE_FAIL = 'WORKEXP_SAVE_FAIL';

export const TECHNOLOGY_LOAD_REQUEST = 'TECHNOLOGY_LOAD_REQUEST';
export const TECHNOLOGY_LOAD_SUCCESS = 'TECHNOLOGY_LOAD_SUCCESS';
export const TECHNOLOGY_LOAD_FAIL = 'TECHNOLOGY_LOAD_FAIL';

export const PROJECT_SAVE_REQUEST = 'PROJECT_SAVE_REQUEST';
export const PROJECT_SAVE_SUCCESS = 'PROJECT_SAVE_SUCCESS';
export const PROJECT_SAVE_FAIL = 'PROJECT_SAVE_FAIL';